<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFJiOtCS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFJiOtCS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFJiOtCS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFJiOtCS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFJiOtCS\App_KernelDevDebugContainer([
    'container.build_hash' => 'FJiOtCS',
    'container.build_id' => '60bf51d8',
    'container.build_time' => 1684287499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFJiOtCS');
