<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6X4UVcO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6X4UVcO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6X4UVcO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6X4UVcO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6X4UVcO\App_KernelDevDebugContainer([
    'container.build_hash' => '6X4UVcO',
    'container.build_id' => '013c1739',
    'container.build_time' => 1681809257,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6X4UVcO');
