<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY3zMY4x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY3zMY4x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY3zMY4x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY3zMY4x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY3zMY4x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y3zMY4x',
    'container.build_id' => '37d4f03b',
    'container.build_time' => 1681499336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY3zMY4x');
