<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.833cb8d0.js',
                'build/751.ae6389df.js',
                'build/app.28e8afd7.js',
            ],
            'css' => [
                'build/app.addc9320.css',
            ],
        ],
    ],
],

]];
